name = "Auto Texture Baker",
author": "maythas_w maythas.wangcharoenwong@gmail.com",
version": (0,0,1),
blender": (2,8,0),
description" : "Automatically bakes selected object's material into texture",
category = Material

schema_version = "1.0.0"
id = "auto_texture_baker"
version = "0.0.2"
name = "Auto Texture Baker"
tagline = "Baking materials to PBR texture in one click"
maintainer = "maythas_w <maythas.wangcharoenwong@gmail.com>"
type = "add-on"
category = "Material"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
# tags = ["Animation", "Sequencer"]

blender_version_min = "2.8.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]